### ISSUE TITLE
question about path_to_groundtruth

### ISSUE THREAD

**Issue by xiaobeikankan** [CVLAB-Unibo/Learning2AdaptForStereo#1]
Dear Sir
 How did you get groundtruth of KITTI datasets in the .csv file ? I have downloaded the dataset before,  however there is no such file .

**Comment by AlessioTonioni** [comment]
Hi,
we have used the depth maps available [here](http://www.cvlibs.net/datasets/kitti/eval_depth.php?benchmark=depth_prediction) converted to disparity using the provided camera intrinsics.
