### ISSUE TITLE
Why pretraining on F3D?

### ISSUE THREAD

**Issue by SpadeLiu** [CVLAB-Unibo/Learning2AdaptForStereo#3]
hi, thanks for your work. I just wonder why you pretrain the model on F3D before L2A-training mode. And why when pretraining the L2A-training mode is not used?

**Comment by AlessioTonioni** [comment]
We tried to start from the beginning with L2A but we were unable to obtain stable convergence. Most likely it's just a matter of hyper parameters selection, but we were not able to find the right combination.
Starting from the F3D pre training is pretty standard practice for deep stereo networks and allow us to start from a model that is already able to predict reasonable disparities.
