### ISSUE TITLE
Question about adaptation？

### ISSUE THREAD

**Issue by wqx854987945** [CVLAB-Unibo/Learning2AdaptForStereo#6]
Thanks for the  great work！
I want to know if  the weighted mask will be updated in online adaptation phase using a small amount of gt labels？

**Comment by wqx854987945** [comment]
If weighted mask is not updated in online adaptation，maybe better unspervised loss can bring better performence？

**Comment by AlessioTonioni** [comment]
No gt labels are used online. The weighted mask is predicted from RGB data and the small network predicting it is not updated. 

Better unsupervised losses can definitely improve performances.
